"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'ru' | 'de'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  ru: {
    // Auth pages
    'auth.login': 'Вход',
    'auth.register': 'Регистрация',
    'auth.accountRegistration': 'Регистрация аккаунта',
    'auth.passwordRecovery': 'Восстановление пароля',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.name': 'Имя',
    'auth.surname': 'Фамилия',
    'auth.phone': 'Номер телефона',
    'auth.enterPhoneNumber': 'Введите номер телефона',
    'auth.repeatPassword': 'Повторите пароль',
    'auth.rememberMe': 'Запомнить меня',
    'auth.forgotPassword': 'Забыли пароль?',
    'auth.signIn': 'Войти',
    'auth.signUp': 'Зарегистрироваться',
    'auth.alreadyHaveAccount': 'Уже есть аккаунт?',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.continue': 'Продолжить',
    'auth.backToLogin': 'Вернуться к входу',
    'auth.byRegisteringAccept': 'Регистрируясь, я принимаю',
    'auth.privacyPolicy': 'Политику конфиденциальности',
    'auth.detectingCountry': 'Определяем страну...',
    'auth.detected': 'Определено',
    'auth.createAccountDescription': 'Создайте новый аккаунт для начала работы',
    'auth.loginDescription': 'Войдите в свой аккаунт',
    'auth.forgotPasswordDescription': 'Введите email для восстановления пароля',
    
    // Email verification
    'auth.verifyEmail': 'Подтвердите email',
    'auth.verifyEmailDescription': 'Мы отправили ссылку для подтверждения на вашу почту',
    'auth.checkYourEmail': 'Проверьте почту',
    'auth.emailSent': 'Письмо отправлено!',
    'auth.verificationSent': 'Мы отправили письмо с подтверждением на {email}',
    'auth.verificationInstructions': 'Нажмите на ссылку в письме, чтобы активировать аккаунт',
    'auth.checkEmailInstructions': 'Проверьте почту {email} и нажмите на ссылку для подтверждения',
    'auth.resendEmail': 'Отправить повторно',
    'auth.didntReceiveEmail': 'Не получили письмо?',
    'auth.checkSpamFolder': 'Проверьте папку "Спам"',
    'auth.verificationError': 'Ошибка при отправке письма',
    'auth.emailNotVerified': 'Email не подтвержден. Проверьте почту и подтвердите регистрацию',
    'auth.alreadyRegistered': 'Аккаунт с таким email уже зарегистрирован. Проверьте почту для подтверждения',
    'auth.emailVerified': 'Email подтвержден',
    'auth.verificationFailed': 'Ошибка подтверждения',
    'auth.emailVerifiedDescription': 'Ваш email успешно подтвержден',
    'auth.verificationFailedDescription': 'Не удалось подтвердить email',
    'auth.verificationSuccess': 'Подтверждение успешно!',
    'auth.canNowLogin': 'Теперь вы можете войти в систему',
    'auth.verificationErrorDescription': 'Ссылка недействительна или истекла',
    
    // Validation messages
    'validation.passwordsNotMatch': 'Пароли не совпадают',
    'validation.passwordMinLength': 'Пароль должен содержать минимум 6 символов',
    'validation.invalidPhoneFormat': 'Неверный формат номера телефона',
    'validation.acceptPrivacy': 'Необходимо принять Политику конфиденциальности',
    'validation.allFieldsRequired': 'Все поля обязательны',
    'validation.userExists': 'Пользователь с таким email уже существует',
    'validation.invalidCredentials': 'Неверный email или пароль',
    'validation.registrationSuccess': 'Регистрация успешна! Теперь войдите в систему.',
    'validation.registrationError': 'Произошла ошибка при регистрации',
    'validation.loginError': 'Произошла ошибка при входе',
    'validation.passwordResetSent': 'Если аккаунт с таким email существует, инструкции для восстановления пароля отправлены на вашу электронную почту',
    'validation.emailRequired': 'Email обязателен',
    'validation.passwordRequired': 'Пароль обязателен',
    'validation.nameRequired': 'Имя обязательно',
    'validation.surnameRequired': 'Фамилия обязательна',
    'validation.phoneRequired': 'Номер телефона обязателен',
    'validation.invalidEmail': 'Введите корректный email',
    'validation.passwordTooShort': 'Пароль слишком короткий',
    'validation.passwordTooLong': 'Пароль слишком длинный',
    'validation.nameTooShort': 'Имя слишком короткое',
    'validation.nameTooLong': 'Имя слишком длинное',
    
    // Dashboard
    'dashboard.hello': 'Привет',
    'dashboard.portfolio': 'Портфель',
    'dashboard.transactions': 'Транзакции',
    'dashboard.analytics': 'Аналитика',
    'dashboard.totalValue': 'Общая стоимость',
    'dashboard.totalOperations': 'Всего операций',
    'dashboard.profitability': 'Прибыльность',
    'dashboard.logout': 'Выйти',
    'dashboard.manageInvestments': 'Управление вашими инвестициями',
    'dashboard.operationHistory': 'История ваших операций',
    'dashboard.statisticsReports': 'Статистика и отчеты',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.signingIn': 'Вход...',
    'common.registering': 'Регистрация...',
    'common.sending': 'Отправка...',
    'common.uploadPhoto': 'Загрузить фото',
    'common.changePhoto': 'Изменить фото',
    'common.remove': 'Удалить',
    'common.photoHint': 'JPEG, PNG, GIF или WebP (до 5MB)',
    'common.uploadDocument': 'Загрузить документ',
    'common.changeDocument': 'Изменить документ',
    'common.uploadDocumentPlaceholder': 'Нажмите для загрузки документа',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',

    // Header
    'header.funds': 'Средства',
    'header.available': 'Доступно',
    'header.margin': 'Маржа',
    'header.profit': 'Прибыль',
    'header.kyiv': 'Москва',
    'header.details': 'Подробнее',
    'header.profile': 'Профиль',
    'header.logout': 'Выйти',

    // Nav
    'nav.assets': 'Активы',
    'nav.accounts': 'Счета',
    'nav.support': 'Поддержка',
    'nav.profile': 'Профиль',

    // Logout dialog
    'common.confirmLogout': 'Подтверждение выхода',
    'common.logoutConfirmMessage': 'Вы уверены, что хотите выйти из системы?',
    'common.logout': 'Выйти',

    // Admin dashboard
    'admin.dashboardTitle': 'Админ-панель',
    'admin.dashboardSubtitle': 'Обзор основных метрик и статистики',
    'admin.clientsToday': 'Клиенты за сегодня',
    'admin.newRegistrationsToday': 'Новые регистрации за сегодня',
    'admin.profit': 'Профит',
    'admin.totalProfit': 'Общая прибыль системы',
    'admin.metricPlaceholderTitle': 'Метрика',
    'admin.metricPlaceholderHint': 'Placeholder для вашей метрики',
    'admin.chart2': 'График 2',
    'admin.chart3': 'График 3',
    'admin.chartPlaceholder': 'Здесь будет график',
    'admin.clientsPeriod': 'Клиенты за период',
    'admin.totalClients': 'Всего клиентов',
    'admin.selectPeriod': 'Выберите период',
    'admin.last3months': 'Последние 3 месяца',
    'admin.last30days': 'Последние 30 дней',
    'admin.last7days': 'Последние 7 дней',
    // Admin sidebar
    'admin.sidebar.title': 'Админ-панель',
    'admin.sidebar.dashboard': 'Дашборд',
    'admin.sidebar.clients': 'Клиенты',
    'admin.sidebar.pairs': 'Пары',
    'admin.sidebar.kyc': 'KYC',
    'admin.sidebar.tickets': 'Обращения',
    'admin.sidebar.transactions': 'Транзакции',
    'admin.sidebar.withdrawals': 'Выводы',
    'admin.sidebar.deals': 'Сделки',
    'admin.sidebar.admins': 'Администраторы',
    'admin.sidebar.settings': 'Настройки',
    'admin.sidebar.settingsGeneral': 'Общие',
    'admin.sidebar.settingsSecurity': 'Безопасность',

    // Admin Tickets
    'admin.tickets.title': 'Обращения в поддержку',
    'admin.tickets.subtitle': 'Управление тикетами клиентов',
    'admin.tickets.loading': 'Загрузка тикетов...',
    'admin.tickets.list': 'Список тикетов',
    'admin.tickets.noTickets': 'Нет тикетов',
    'admin.tickets.selectTicket': 'Выберите тикет для просмотра',
    'admin.tickets.client': 'Клиент',
    'admin.tickets.support': 'Поддержка',
    'admin.tickets.writeReply': 'Написать ответ...',
    'admin.tickets.replySent': 'Ответ отправлен',
    'admin.tickets.statusUpdated': 'Статус обновлен',
    'admin.tickets.messageUpdated': 'Сообщение обновлено',
    'admin.tickets.error': 'Ошибка',
    'admin.tickets.updateError': 'Не удалось обновить сообщение',
    'admin.tickets.updateErrorDesc': 'Произошла ошибка при обновлении сообщения',
    'admin.tickets.editMessage': 'Редактировать сообщение',
    'admin.tickets.save': 'Сохранить',
    'admin.tickets.saving': 'Сохранение...',
    'admin.tickets.cancel': 'Отмена',
    'admin.tickets.saveHint': 'Ctrl+Enter для сохранения, Esc для отмены',
    'admin.tickets.status.all': 'Все',
    'admin.tickets.status.open': 'Открытые',
    'admin.tickets.status.inProgress': 'В работе',
    'admin.tickets.status.awaitingReply': 'Ожидают ответа',
    'admin.tickets.status.resolved': 'Решены',
    'admin.tickets.status.closed': 'Закрыты',
    'admin.tickets.status.openSingle': 'Открыт',
    'admin.tickets.status.inProgressSingle': 'В работе',
    'admin.tickets.status.awaitingReplySingle': 'Ожидает ответа',
    'admin.tickets.status.resolvedSingle': 'Решен',
    'admin.tickets.status.closedSingle': 'Закрыт',

    // Admin Clients
    'admin.clients.title': 'Клиенты',
    'admin.clients.subtitle': 'Управление клиентами системы',
    'admin.clients.delete': 'Удалить',
    'admin.clients.deleteSelected': 'Удалить ({count})',
    'admin.clients.export': 'Export CSV',
    'admin.clients.exporting': 'Экспорт...',
    'admin.clients.addClient': 'Добавить клиента',
    'admin.clients.list': 'Список клиентов',
    'admin.clients.resetFilters': 'Сбросить фильтры',
    'admin.clients.searchByName': 'Поиск по имени...',
    'admin.clients.searchByEmail': 'Поиск по email...',
    'admin.clients.searchByPhone': 'Поиск по телефону...',
    'admin.clients.verification': 'Верификация',
    'admin.clients.verificationAll': 'Все',
    'admin.clients.verificationYes': 'Верифицированные',
    'admin.clients.verificationNo': 'Не верифицированные',
    'admin.clients.loading': 'Загрузка...',
    'admin.clients.noClients': 'Нет клиентов',
    'admin.clients.shown': 'Показано {shown} из {total} клиентов',
    'admin.clients.page': 'Страница {current} из {total}',
    'admin.clients.prev': 'Назад',
    'admin.clients.next': 'Вперед',
    'admin.clients.create': 'Создать клиента',
    'admin.clients.createDesc': 'Добавьте нового клиента в систему',
    'admin.clients.edit': 'Редактировать клиента',
    'admin.clients.editDesc': 'Измените данные клиента',
    'admin.clients.deleteConfirm': 'Удалить клиента',
    'admin.clients.deleteConfirmDesc': 'Вы уверены, что хотите удалить клиента {email}? Это действие нельзя отменить.',
    'admin.clients.name': 'Имя',
    'admin.clients.email': 'Email',
    'admin.clients.password': 'Пароль',
    'admin.clients.passwordNew': 'Новый пароль (оставьте пустым, чтобы не менять)',
    'admin.clients.phone': 'Телефон',
    'admin.clients.emailVerified': 'Email верифицирован',
    'admin.clients.createButton': 'Создать',
    'admin.clients.saveButton': 'Сохранить',
    'admin.clients.deleteButton': 'Удалить',
    'admin.clients.generatePassword': 'Сгенерировать пароль',
    'admin.clients.createError': 'Ошибка создания клиента',
    'admin.clients.updateError': 'Ошибка обновления клиента',
    'admin.clients.deleteError': 'Ошибка удаления клиента',
    'admin.clients.exportError': 'Не удалось выполнить экспорт',
    'admin.clients.bulkDeleteConfirm': 'Удалить {count} клиент(ов)?',
    'admin.clients.bulkDeleteError': 'Ошибка при удалении',
    'admin.clients.columns.status': 'Статус',
    'admin.clients.columns.name': 'Имя',
    'admin.clients.columns.email': 'Email',
    'admin.clients.columns.phone': 'Телефон',
    'admin.clients.columns.wallets': 'Кошельки',
    'admin.clients.columns.accounts': 'Счета',
    'admin.clients.columns.balance': 'Баланс',
    'admin.clients.columns.verified': 'Верификация',
    'admin.clients.columns.active': 'Активность',
    'admin.clients.columns.created': 'Создан',
    'admin.clients.columns.actions': 'Действия',
    'admin.clients.status.online': 'Online',
    'admin.clients.status.offline': 'Offline',
    'admin.clients.verified.yes': 'Да',
    'admin.clients.verified.no': 'Нет',
    'admin.clients.active.active': 'Активен',
    'admin.clients.active.blocked': 'Заблокирован',

    // Admin KYC
    'admin.kyc.title': 'KYC верификация',
    'admin.kyc.subtitle': 'Управление заявками на верификацию',
    'admin.kyc.loading': 'Загрузка...',
    'admin.kyc.error': 'Ошибка',
    'admin.kyc.networkError': 'Ошибка сети',
    'admin.kyc.loadError': 'Не удалось загрузить заявки',
    'admin.kyc.status.all': 'Все',
    'admin.kyc.status.draft': 'Черновик',
    'admin.kyc.status.pending': 'На проверке',
    'admin.kyc.status.approved': 'Одобрено',
    'admin.kyc.status.rejected': 'Отклонено',
    'admin.kyc.status.resubmit': 'Требуется повтор',
    'admin.kyc.review': 'Рассмотреть',
    'admin.kyc.submitReview': 'Отправить решение',
    'admin.kyc.submitting': 'Отправка...',
    'admin.kyc.reviewSuccess': 'Решение отправлено',
    'admin.kyc.reviewError': 'Ошибка отправки решения',
    'admin.kyc.selectStatus': 'Выберите статус',
    'admin.kyc.notes': 'Комментарии',
    'admin.kyc.notesPlaceholder': 'Введите комментарии (опционально)',
    'admin.kyc.cancel': 'Отмена',
    'admin.kyc.client': 'Клиент',
    'admin.kyc.submitted': 'Отправлено',
    'admin.kyc.reviewed': 'Рассмотрено',
    'admin.kyc.noRequests': 'Нет заявок',

    // Admin Pairs
    'admin.pairs.title': 'Торговые пары',
    'admin.pairs.subtitle': 'Управление торговыми парами',
    'admin.pairs.loading': 'Загрузка...',
    'admin.pairs.refresh': 'Обновить',
    'admin.pairs.import': 'Массовый импорт',
    'admin.pairs.add': 'Добавить пару',
    'admin.pairs.edit': 'Редактировать',
    'admin.pairs.delete': 'Удалить',
    'admin.pairs.symbol': 'Символ',
    'admin.pairs.name': 'Название',
    'admin.pairs.type': 'Тип',
    'admin.pairs.market': 'Рынок',
    'admin.pairs.minQty': 'Мин. объем',
    'admin.pairs.qtyStep': 'Шаг объема',
    'admin.pairs.priceStep': 'Шаг цены',
    'admin.pairs.leverage': 'Плечо',
    'admin.pairs.mmr': 'MMR',
    'admin.pairs.feeTaker': 'Комиссия Taker',
    'admin.pairs.feeMaker': 'Комиссия Maker',
    'admin.pairs.markPriceSource': 'Источник маркировочной цены',
    'admin.pairs.created': 'Создано',
    'admin.pairs.updated': 'Обновлено',
    'admin.pairs.noPairs': 'Нет торговых пар',

    // Admin Transactions
    'admin.transactions.title': 'Транзакции',
    'admin.transactions.subtitle': 'История всех транзакций в системе',

    // Admin Withdrawals
    'admin.withdrawals.title': 'Выводы средств',
    'admin.withdrawals.subtitle': 'Управление запросами на вывод средств',

    // Admin Client Details
    'admin.clientDetails.back': 'Назад к списку',
    'admin.clientDetails.loading': 'Загрузка...',
    'admin.clientDetails.save': 'Сохранить',
    'admin.clientDetails.saving': 'Сохранение...',
    'admin.clientDetails.saved': 'Изменения сохранены',
    'admin.clientDetails.saveError': 'Ошибка сохранения',
    'admin.clientDetails.tabs.profile': 'Профиль',
    'admin.clientDetails.tabs.accounts': 'Счета',
    'admin.clientDetails.tabs.deals': 'Сделки',
    'admin.clientDetails.tabs.wallets': 'Кошельки',
    'admin.clientDetails.profile.title': 'Профиль клиента',
    'admin.clientDetails.profile.name': 'Имя',
    'admin.clientDetails.profile.email': 'Email',
    'admin.clientDetails.profile.phone': 'Телефон',
    'admin.clientDetails.profile.password': 'Пароль',
    'admin.clientDetails.profile.emailVerified': 'Email верифицирован',
    'admin.clientDetails.profile.isActive': 'Активен',
    'admin.clientDetails.profile.accessLevel': 'Уровень доступа',
    'admin.clientDetails.profile.accessLevelBase': 'Базовый',
    'admin.clientDetails.profile.accessLevelFull': 'Полный',
    'admin.clientDetails.profile.depositRequired': 'Требуемый депозит',
    'admin.clientDetails.accounts.title': 'Счета клиента',
    'admin.clientDetails.accounts.demoTopup': 'Пополнение демо-счета',
    'admin.clientDetails.accounts.demoTopupDesc': 'Быстрое пополнение демо-баланса клиента',
    'admin.clientDetails.accounts.topupAmount': 'Сумма пополнения ($)',
    'admin.clientDetails.accounts.topup': 'Пополнить',
    'admin.clientDetails.accounts.toppingUp': 'Пополнение...',
    'admin.clientDetails.accounts.topupHint': 'Пополнение применяется к первому найденному демо-счету клиента. Если демо-счета нет, он будет создан автоматически.',
    'admin.clientDetails.accounts.financial': 'Финансовые счета',
    'admin.clientDetails.accounts.trading': 'Торговые счета',
    'admin.clientDetails.accounts.noAccounts': 'Нет счетов',
    'admin.clientDetails.deals.title': 'Сделки клиента',
    'admin.clientDetails.deals.loading': 'Загрузка сделок...',
    'admin.clientDetails.deals.noDeals': 'Нет сделок',
    'admin.clientDetails.wallets.title': 'Кошельки клиента',
    'admin.clientDetails.wallets.loading': 'Загрузка кошельков...',
    'admin.clientDetails.wallets.noWallets': 'Нет кошельков',
    'admin.clientDetails.wallets.create': 'Создать кошелек',
    'admin.clientDetails.wallets.type': 'Тип',
    'admin.clientDetails.wallets.address': 'Адрес',
    'admin.clientDetails.wallets.created': 'Создан',

    // Portfolio
    'portfolio.title': 'Портфолио',
    'portfolio.all': 'Все сделки',
    'portfolio.open': 'Открытые',
    'portfolio.closed': 'Закрытые',
    'portfolio.totalTrades': 'Всего сделок',
    'portfolio.openCount': 'Открытые',
    'portfolio.realizedPnl': 'Реализованный PnL',
    'portfolio.unrealizedPnl': 'Нереализованный PnL',
    'portfolio.trades': 'Сделки',
    'portfolio.noDeals': 'Нет сделок',
    'portfolio.loading': 'Загрузка...',
    'portfolio.tradeOpen': 'Открыта',
    'portfolio.tradeClosed': 'Закрыта',
    'portfolio.long': 'Long',
    'portfolio.short': 'Short',

    // Messages
    'messages.support': 'Поддержка',
    'messages.yourTickets': 'Ваши обращения',
    'messages.new': 'Новое обращение',
    'messages.subject': 'Тема',
    'messages.subjectPlaceholder': 'Кратко опишите проблему',
    'messages.priority': 'Приоритет',
    'messages.message': 'Сообщение',
    'messages.messagePlaceholder': 'Подробно опишите вашу проблему',
    'messages.writeMessage': 'Написать сообщение...',
    'messages.create': 'Создать обращение',
    'messages.cancel': 'Отмена',
    'messages.noTickets': 'У вас пока нет обращений',
    'messages.selectOrCreate': 'Выберите обращение или создайте новое',
    'messages.loadingTickets': 'Загрузка обращений...',
    'messages.loadingDetails': 'Загрузка деталей...',
    'messages.low': 'Низкий',
    'messages.medium': 'Средний',
    'messages.high': 'Высокий',
    'messages.urgent': 'Срочный',

    // Positions accordion
    'positions.openTrades': 'Открытые сделки',
    'positions.collapse': 'Свернуть',
    'positions.expand': 'Развернуть',
    'positions.noOpen': 'Нет открытых сделок',
    'positions.marginLocked': 'Заблокированная маржа',
    'positions.tradeDetails': 'Детали сделки',
    'positions.openPosition': 'Открытая позиция',
    'positions.closedPosition': 'Закрытая позиция',
    'positions.id': 'ID сделки',
    'positions.status': 'Статус',
    'positions.type': 'Тип',
    'positions.entryPrice': 'Цена входа',
    'positions.leverage': 'Плечо',
    'positions.mode': 'Режим',
    'positions.qty': 'Объем',
    'positions.createdAt': 'Дата создания',
    'positions.updatedAt': 'Дата обновления',
    'positions.liqPrice': 'Ликвидация',
    'positions.markPrice': 'Текущая цена',
    'positions.currentPnl': 'Текущий PnL',
    'positions.roe': 'ROE (%)',
    'positions.closing': 'Закрытие...',
    'positions.closePosition': 'Закрыть позицию',

    // Trading panel
    'trade.buy': 'Купить',
    'trade.sell': 'Продать',
    'trade.maintenanceMargin': 'Поддерживающая маржа',
    'trade.initialMargin': 'Начальная маржа',
    'trade.highRisk': 'Высокий риск',
    'trade.required': 'Требуется',
    'trade.tradingBlocked': 'Торговля запрещена',
    'trade.fullAccessRequired': 'Требуется полный уровень доступа',
    'trade.notAllowedForSymbol': 'Недоступно для данного символа',
    'common.unavailable': 'недоступно',
    'pairs.search': 'Поиск пары',
    'pairs.nothingFound': 'Ничего не найдено',
    'pairs.favorites': 'Избранное',

    // Accounts
    'accounts.tabs.accounts': 'Счета',
    'accounts.tabs.deposit': 'Пополнить',
    'accounts.tabs.transfer': 'Перевести',
    'accounts.tabs.history': 'История',
    'accounts.financialAccounts': 'Финансовые счета',
    'accounts.tradingAccounts': 'Торговые счета',
    'accounts.transfer': 'Перевести',
    'accounts.deposit': 'Пополнить',
    'accounts.otherWallets': 'Другие кошельки',
    'accounts.liveAccount': 'LIVE счет',
    'accounts.demoAccount': 'DEMO счет',
    'accounts.history.title': 'История платежей:',
    'accounts.history.subtitle': 'Здесь вы можете посмотреть свою историю вводов и выводов',
    'accounts.history.id': 'ID',
    'accounts.history.date': 'Дата',
    'accounts.history.operation': 'Операция',
    'accounts.history.amount': 'Сумма',
    'accounts.history.download': 'Скачать историю',
    'accounts.deposit.title': 'Пополнение финансового счета:',
    'accounts.deposit.subtitle': 'Мы никак не влияем на время обработки платежа. В случае проблем обратитесь в поддержку',
    'accounts.deposit.notice': 'Внимание! Минимальная сумма операции 100 USD',
    'accounts.deposit.to': 'Куда:',
    'accounts.deposit.amountToSend': 'Сумма к отправке:',
    'accounts.deposit.usdEquivalent': 'Эквивалент в долларах:',
    'accounts.deposit.submit': 'Пополнить',
    'accounts.transfer.title': 'Перевод между счетами:',
    'accounts.transfer.from': 'Откуда:',
    'accounts.transfer.to': 'Куда:',
    'accounts.transfer.amount': 'Сумма перевода:',
    'accounts.transfer.creditAmount': 'Сумма к зачислению:',
    'accounts.transfer.submit': 'Перевести',

    // Deposit Ticket
    'depositTicket.title': 'Пополнение',
    'depositTicket.description': 'Отправьте криптовалюту на указанный адрес',
    'depositTicket.status.completed': 'Завершено',
    'depositTicket.status.pending': 'Ожидание',
    'depositTicket.status.expired': 'Истекло',
    'depositTicket.status.failed': 'Ошибка',
    'depositTicket.loading': 'Загрузка...',
    'depositTicket.notFound': 'Тикет не найден',
    'depositTicket.backToDeposit': 'Вернуться к пополнению',
    'depositTicket.completed.title': 'Средства получены!',
    'depositTicket.completed.description': 'Ваш баланс был успешно обновлен',
    'depositTicket.completed.txId': 'Transaction ID',
    'depositTicket.completed.backToAccounts': 'Вернуться к счетам',
    'depositTicket.expired.title': 'Время истекло',
    'depositTicket.expired.description': 'Создайте новый тикет для пополнения',
    'depositTicket.expired.createNew': 'Создать новый тикет',
    'depositTicket.failed.title': 'Ошибка пополнения',
    'depositTicket.failed.description': 'Пополнение не удалось. Обратитесь в поддержку.',
    'depositTicket.timeRemaining': 'Осталось времени',
    'depositTicket.amountInUSD': 'Сумма в USD',
    'depositTicket.amountIn': 'Сумма в',
    'depositTicket.rate': 'Курс',
    'depositTicket.loadingRate': 'Загрузка курса...',
    'depositTicket.address': 'Адрес для пополнения',
    'depositTicket.copy': 'Копировать',
    'depositTicket.copied': 'Адрес скопирован!',
    'depositTicket.info.ticket': 'Тикет',
    'depositTicket.info.sendOnly': 'Отправляйте только',
    'depositTicket.info.onThisAddress': 'на этот адрес',
    'depositTicket.info.confirmation': 'Зачисление произойдет после подтверждения сети (обычно 1-3 минуты)',
    'depositTicket.info.autoCheck': 'Статус проверяется автоматически каждые 10 секунд',

    // Profile
    'profile.tabs.info': 'Персональные данные',
    'profile.tabs.verification': 'Верификация',
    'profile.tabs.twofa': 'Двухфакторная аутентификация',
    'profile.tabs.password': 'Смена пароля',
    'profile.loading': 'Загрузка профиля...',
    'profile.name': 'Имя',
    'profile.surname': 'Фамилия',
    'profile.gender': 'Пол',
    'profile.dob': 'Дата рождения',
    'profile.country': 'Страна',
    'profile.city': 'Город',
    'profile.address': 'Адрес',
    'profile.postcode': 'Почтовый индекс',
    'profile.email': 'Email',
    'profile.phone': 'Телефон',
    'profile.gender.male': 'Мужской',
    'profile.gender.female': 'Женский',

    // Profile (mobile tabs)
    'profile.tabs.mobile.info': 'Персональные данные',
    'profile.tabs.mobile.verification': 'Верификация',
    'profile.tabs.mobile.2fa': 'Двухфакторная аутентификация',
    'profile.tabs.mobile.password': 'Смена пароля',
    // Profile toasts and labels
    'profile.loadError.title': 'Не удалось загрузить профиль',
    'profile.loadError.desc': 'Обновите страницу и попробуйте снова',
    'profile.imageSaveError.title': 'Не удалось сохранить фото',
    'profile.imageSaveError.desc': 'Попробуйте позже',
    'profile.photoUpdated.title': 'Фото профиля обновлено!',
    'profile.photoUpdated.desc': 'Изменения успешно сохранены',
    'profile.photoRemoved.title': 'Фото профиля удалено!',
    'profile.photoRemoved.desc': 'Изменения успешно сохранены',
    'profile.saveSuccess.title': 'Профиль сохранен!',
    'profile.saveSuccess.desc': 'Все изменения успешно сохранены',
    'profile.saveFailed.title': 'Не удалось сохранить профиль',
    'profile.saveFailed.desc': 'Проверьте данные и попробуйте снова',
    'profile.networkError.title': 'Сбой сети',
    'profile.networkError.desc': 'Не удалось выполнить операцию. Повторите попытку',
    // Verification
    'profile.verif.loading': 'Загрузка данных верификации...',
    'profile.verif.status': 'Статус верификации:',
    'profile.verif.identityVerified': '✅ Ваша личность успешно верифицирована!',
    'profile.verif.rejected': '❌ Верификация отклонена. Загрузите новые документы и попробуйте снова.',
    'profile.verif.pending': '⏳ Документы на проверке. Уведомим в течение 24–48 часов.',
    'profile.verif.pendingNote': 'Документы отправлены на рассмотрение. Мы сообщим результат по электронной почте.',
    'profile.verif.approvedNote': 'Документы успешно верифицированы.',
    'profile.verif.instructions': 'Пожалуйста, загрузите четкие фотографии вашего государственного удостоверения личности (паспорт, водительские права и т.д.)',
    'profile.verif.frontTitle': 'Лицевая сторона документа',
    'profile.verif.frontDesc': 'Загрузите лицевую сторону. Убедитесь, что текст читабелен.',
    'profile.verif.backTitle': 'Обратная сторона / Селфи',
    'profile.verif.backDesc': 'Загрузите оборотную сторону документа или селфи с документом.',
    'profile.verif.submit': 'Отправить на проверку',
    'profile.verif.submitting': 'Отправка...',
    'profile.verif.lastSubmitted': 'Последняя отправка:',
    'profile.verif.notAuthorized.title': 'Не авторизован',
    'profile.verif.notAuthorized.desc': 'Войдите в систему, чтобы загрузить документы',
    'profile.verif.saveDocError.title': 'Не удалось сохранить документ',
    'profile.verif.saveDocError.desc': 'Попробуйте позже',
    'profile.verif.docSaved.title': 'Документ сохранен!',
    'profile.verif.docSaved.uploaded': 'Документ загружен успешно',
    'profile.verif.docSaved.removed': 'Документ удален успешно',
    'profile.verif.docsRequired.title': 'Требуются документы',
    'profile.verif.docsRequired.desc': 'Загрузите фото лицевой и оборотной стороны',
    'profile.verif.submitFailed.title': 'Ошибка отправки',
    'profile.verif.submitFailed.desc': 'Не удалось отправить документы. Попробуйте снова',
    // 2FA
    'profile.2fa.loading': 'Загрузка настроек 2FA...',
    'profile.2fa.recommend': 'Рекомендуем включить 2FA для защиты аккаунта.',
    'profile.2fa.enabled': '2FA включена',
    'profile.2fa.disabled': '2FA отключена',
    'profile.2fa.setup': 'Настроить 2FA',
    'profile.2fa.preparing': 'Подготовка...',
    'profile.2fa.disable': 'Отключить 2FA',
    'profile.2fa.disabling': 'Отключение...',
    'profile.2fa.scanQr': 'Отсканируйте этот QR-код в Google Authenticator или введите секрет вручную.',
    'profile.2fa.openOtpauth': 'Открыть otpauth ссылку',
    'profile.2fa.secret': 'Секрет:',
    'profile.2fa.enterCode': 'Введите 6-значный код',
    'profile.2fa.verify': 'Подтвердить',
    'profile.2fa.verifying': 'Проверка...',
    // Password
    'profile.password.old': 'Старый пароль:',
    'profile.password.new': 'Новый пароль:',
    'profile.password.repeat': 'Повторите новый пароль:',
    'profile.password.help': 'Если вы не помните старый пароль, пожалуйста, свяжитесь со службой поддержки',
    'profile.password.change': 'Изменить',
  },
  de: {
    // Auth pages
    'auth.login': 'Anmelden',
    'auth.register': 'Registrieren',
    'auth.accountRegistration': 'Konto-Registrierung',
    'auth.passwordRecovery': 'Passwort-Wiederherstellung',
    'auth.email': 'Email',
    'auth.password': 'Passwort',
    'auth.name': 'Name',
    'auth.surname': 'Nachname',
    'auth.phone': 'Telefonnummer',
    'auth.enterPhoneNumber': 'Telefonnummer eingeben',
    'auth.repeatPassword': 'Passwort wiederholen',
    'auth.rememberMe': 'Angemeldet bleiben',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.signIn': 'Anmelden',
    'auth.signUp': 'Registrieren',
    'auth.alreadyHaveAccount': 'Bereits ein Konto?',
    'auth.noAccount': 'Kein Konto?',
    'auth.continue': 'Weiter',
    'auth.backToLogin': 'Zurück zur Anmeldung',
    'auth.byRegisteringAccept': 'Durch die Registrierung akzeptiere ich die',
    'auth.privacyPolicy': 'Datenschutzrichtlinie',
    'auth.detectingCountry': 'Land wird erkannt...',
    'auth.detected': 'Erkannt',
    'auth.createAccountDescription': 'Erstellen Sie ein neues Konto für den Start',
    'auth.loginDescription': 'Melden Sie sich in Ihrem Konto an',
    'auth.forgotPasswordDescription': 'Geben Sie die E-Mail für die Passwort-Wiederherstellung ein',
    
    // Email verification
    'auth.verifyEmail': 'E-Mail bestätigen',
    'auth.verifyEmailDescription': 'Wir haben einen Bestätigungslink an Ihre E-Mail gesendet',
    'auth.checkYourEmail': 'Überprüfen Sie Ihre E-Mail',
    'auth.emailSent': 'E-Mail gesendet!',
    'auth.verificationSent': 'Wir haben eine Bestätigungs-E-Mail an {email} gesendet',
    'auth.verificationInstructions': 'Klicken Sie auf den Link in der E-Mail, um das Konto zu aktivieren',
    'auth.checkEmailInstructions': 'Überprüfen Sie {email} und klicken Sie auf den Bestätigungslink',
    'auth.resendEmail': 'Erneut senden',
    'auth.didntReceiveEmail': 'Keine E-Mail erhalten?',
    'auth.checkSpamFolder': 'Überprüfen Sie den Spam-Ordner',
    'auth.verificationError': 'Fehler beim Senden der E-Mail',
    'auth.emailNotVerified': 'E-Mail nicht bestätigt. Überprüfen Sie Ihre E-Mail und bestätigen Sie die Registrierung',
    'auth.alreadyRegistered': 'Konto mit dieser E-Mail bereits registriert. Überprüfen Sie Ihre E-Mail zur Bestätigung',
    
    // Validation messages
    'validation.passwordsNotMatch': 'Passwörter stimmen nicht überein',
    'validation.passwordMinLength': 'Passwort muss mindestens 6 Zeichen enthalten',
    'validation.invalidPhoneFormat': 'Ungültiges Telefonnummer-Format',
    'validation.acceptPrivacy': 'Sie müssen die Datenschutzrichtlinie akzeptieren',
    'validation.allFieldsRequired': 'Alle Felder sind erforderlich',
    'validation.userExists': 'Benutzer mit dieser E-Mail existiert bereits',
    'validation.invalidCredentials': 'Ungültige E-Mail oder Passwort',
    'validation.registrationSuccess': 'Registrierung erfolgreich! Jetzt anmelden.',
    'validation.registrationError': 'Fehler bei der Registrierung aufgetreten',
    'validation.loginError': 'Fehler bei der Anmeldung aufgetreten',
    'validation.passwordResetSent': 'Falls ein Konto mit dieser E-Mail existiert, wurden Anweisungen zur Passwort-Wiederherstellung an Ihre E-Mail gesendet',
    'validation.emailRequired': 'E-Mail ist erforderlich',
    'validation.passwordRequired': 'Passwort ist erforderlich',
    'validation.nameRequired': 'Name ist erforderlich',
    'validation.surnameRequired': 'Nachname ist erforderlich',
    'validation.phoneRequired': 'Telefonnummer ist erforderlich',
    'validation.invalidEmail': 'Geben Sie eine gültige E-Mail ein',
    'validation.passwordTooShort': 'Passwort ist zu kurz',
    'validation.passwordTooLong': 'Passwort ist zu lang',
    'validation.nameTooShort': 'Name ist zu kurz',
    'validation.nameTooLong': 'Name ist zu lang',
    
    // Dashboard
    'dashboard.hello': 'Hallo',
    'dashboard.portfolio': 'Portfolio',
    'dashboard.transactions': 'Transaktionen',
    'dashboard.analytics': 'Analytik',
    'dashboard.totalValue': 'Gesamtwert',
    'dashboard.totalOperations': 'Gesamtoperationen',
    'dashboard.profitability': 'Rentabilität',
    'dashboard.logout': 'Abmelden',
    'dashboard.manageInvestments': 'Verwalten Sie Ihre Investitionen',
    'dashboard.operationHistory': 'Ihre Operationshistorie',
    'dashboard.statisticsReports': 'Statistiken und Berichte',
    
    // Common
    'common.loading': 'Laden...',
    'common.signingIn': 'Anmelden...',
    'common.registering': 'Registrieren...',
    'common.sending': 'Senden...',
    'common.uploadPhoto': 'Foto hochladen',
    'common.changePhoto': 'Foto ändern',
    'common.remove': 'Entfernen',
    'common.photoHint': 'JPEG, PNG, GIF oder WebP (bis 5MB)',
    'common.uploadDocument': 'Dokument hochladen',
    'common.changeDocument': 'Dokument ändern',
    'common.uploadDocumentPlaceholder': 'Zum Hochladen klicken',
    'common.save': 'Speichern',
    'common.cancel': 'Abbrechen',

    // Header
    'header.funds': 'Mittel',
    'header.available': 'Verfügbar',
    'header.margin': 'Marge',
    'header.profit': 'Gewinn',
    'header.kyiv': 'Moskau',
    'header.details': 'Details',
    'header.profile': 'Profil',
    'header.logout': 'Abmelden',

    // Nav
    'nav.assets': 'Vermögenswerte',
    'nav.accounts': 'Konten',
    'nav.support': 'Support',
    'nav.profile': 'Profil',

    // Logout dialog
    'common.confirmLogout': 'Abmeldung bestätigen',
    'common.logoutConfirmMessage': 'Sind Sie sicher, dass Sie sich abmelden möchten?',
    'common.logout': 'Abmelden',

    // Admin dashboard
    'admin.dashboardTitle': 'Admin-Panel',
    'admin.dashboardSubtitle': 'Übersicht der Hauptmetriken und Statistiken',
    'admin.clientsToday': 'Kunden heute',
    'admin.newRegistrationsToday': 'Neue Registrierungen heute',
    'admin.profit': 'Profit',
    'admin.totalProfit': 'Gesamtprofit des Systems',
    'admin.metricPlaceholderTitle': 'Metrik',
    'admin.metricPlaceholderHint': 'Platzhalter für Ihre Metrik',
    'admin.chart2': 'Diagramm 2',
    'admin.chart3': 'Diagramm 3',
    'admin.chartPlaceholder': 'Hier wird ein Diagramm angezeigt',
    'admin.clientsPeriod': 'Kunden im Zeitraum',
    'admin.totalClients': 'Gesamtkunden',
    'admin.selectPeriod': 'Zeitraum auswählen',
    'admin.last3months': 'Letzte 3 Monate',
    'admin.last30days': 'Letzte 30 Tage',
    'admin.last7days': 'Letzte 7 Tage',
    // Admin sidebar
    'admin.sidebar.title': 'Admin-Panel',
    'admin.sidebar.dashboard': 'Dashboard',
    'admin.sidebar.clients': 'Kunden',
    'admin.sidebar.pairs': 'Paare',
    'admin.sidebar.kyc': 'KYC',
    'admin.sidebar.tickets': 'Anfragen',
    'admin.sidebar.transactions': 'Transaktionen',
    'admin.sidebar.withdrawals': 'Auszahlungen',
    'admin.sidebar.deals': 'Trades',
    'admin.sidebar.admins': 'Administratoren',
    'admin.sidebar.settings': 'Einstellungen',
    'admin.sidebar.settingsGeneral': 'Allgemein',
    'admin.sidebar.settingsSecurity': 'Sicherheit',

    // Admin Tickets
    'admin.tickets.title': 'Support-Anfragen',
    'admin.tickets.subtitle': 'Kundenanfragen verwalten',
    'admin.tickets.loading': 'Anfragen werden geladen...',
    'admin.tickets.list': 'Anfragenliste',
    'admin.tickets.noTickets': 'Keine Anfragen',
    'admin.tickets.selectTicket': 'Wählen Sie eine Anfrage zum Anzeigen',
    'admin.tickets.client': 'Kunde',
    'admin.tickets.support': 'Support',
    'admin.tickets.writeReply': 'Antwort schreiben...',
    'admin.tickets.replySent': 'Antwort gesendet',
    'admin.tickets.statusUpdated': 'Status aktualisiert',
    'admin.tickets.messageUpdated': 'Nachricht aktualisiert',
    'admin.tickets.error': 'Fehler',
    'admin.tickets.updateError': 'Nachricht konnte nicht aktualisiert werden',
    'admin.tickets.updateErrorDesc': 'Beim Aktualisieren der Nachricht ist ein Fehler aufgetreten',
    'admin.tickets.editMessage': 'Nachricht bearbeiten',
    'admin.tickets.save': 'Speichern',
    'admin.tickets.saving': 'Wird gespeichert...',
    'admin.tickets.cancel': 'Abbrechen',
    'admin.tickets.saveHint': 'Strg+Eingabe zum Speichern, Esc zum Abbrechen',
    'admin.tickets.status.all': 'Alle',
    'admin.tickets.status.open': 'Offen',
    'admin.tickets.status.inProgress': 'In Bearbeitung',
    'admin.tickets.status.awaitingReply': 'Warten auf Antwort',
    'admin.tickets.status.resolved': 'Gelöst',
    'admin.tickets.status.closed': 'Geschlossen',
    'admin.tickets.status.openSingle': 'Offen',
    'admin.tickets.status.inProgressSingle': 'In Bearbeitung',
    'admin.tickets.status.awaitingReplySingle': 'Warten auf Antwort',
    'admin.tickets.status.resolvedSingle': 'Gelöst',
    'admin.tickets.status.closedSingle': 'Geschlossen',

    // Admin Clients
    'admin.clients.title': 'Kunden',
    'admin.clients.subtitle': 'Systemkunden verwalten',
    'admin.clients.delete': 'Löschen',
    'admin.clients.deleteSelected': 'Löschen ({count})',
    'admin.clients.export': 'CSV exportieren',
    'admin.clients.exporting': 'Wird exportiert...',
    'admin.clients.addClient': 'Kunde hinzufügen',
    'admin.clients.list': 'Kundenliste',
    'admin.clients.resetFilters': 'Filter zurücksetzen',
    'admin.clients.searchByName': 'Nach Name suchen...',
    'admin.clients.searchByEmail': 'Nach E-Mail suchen...',
    'admin.clients.searchByPhone': 'Nach Telefon suchen...',
    'admin.clients.verification': 'Verifizierung',
    'admin.clients.verificationAll': 'Alle',
    'admin.clients.verificationYes': 'Verifiziert',
    'admin.clients.verificationNo': 'Nicht verifiziert',
    'admin.clients.loading': 'Wird geladen...',
    'admin.clients.noClients': 'Keine Kunden',
    'admin.clients.shown': '{shown} von {total} Kunden angezeigt',
    'admin.clients.page': 'Seite {current} von {total}',
    'admin.clients.prev': 'Zurück',
    'admin.clients.next': 'Weiter',
    'admin.clients.create': 'Kunde erstellen',
    'admin.clients.createDesc': 'Neuen Kunden zum System hinzufügen',
    'admin.clients.edit': 'Kunde bearbeiten',
    'admin.clients.editDesc': 'Kundendaten ändern',
    'admin.clients.deleteConfirm': 'Kunde löschen',
    'admin.clients.deleteConfirmDesc': 'Sind Sie sicher, dass Sie den Kunden {email} löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.',
    'admin.clients.name': 'Name',
    'admin.clients.email': 'E-Mail',
    'admin.clients.password': 'Passwort',
    'admin.clients.passwordNew': 'Neues Passwort (leer lassen, um aktuelles beizubehalten)',
    'admin.clients.phone': 'Telefon',
    'admin.clients.emailVerified': 'E-Mail verifiziert',
    'admin.clients.createButton': 'Erstellen',
    'admin.clients.saveButton': 'Speichern',
    'admin.clients.deleteButton': 'Löschen',
    'admin.clients.generatePassword': 'Passwort generieren',
    'admin.clients.createError': 'Fehler beim Erstellen des Kunden',
    'admin.clients.updateError': 'Fehler beim Aktualisieren des Kunden',
    'admin.clients.deleteError': 'Fehler beim Löschen des Kunden',
    'admin.clients.exportError': 'Export fehlgeschlagen',
    'admin.clients.bulkDeleteConfirm': '{count} Kunde(n) löschen?',
    'admin.clients.bulkDeleteError': 'Fehler beim Löschen',
    'admin.clients.columns.status': 'Status',
    'admin.clients.columns.name': 'Name',
    'admin.clients.columns.email': 'E-Mail',
    'admin.clients.columns.phone': 'Telefon',
    'admin.clients.columns.wallets': 'Brieftaschen',
    'admin.clients.columns.accounts': 'Konten',
    'admin.clients.columns.balance': 'Guthaben',
    'admin.clients.columns.verified': 'Verifiziert',
    'admin.clients.columns.active': 'Aktiv',
    'admin.clients.columns.created': 'Erstellt',
    'admin.clients.columns.actions': 'Aktionen',
    'admin.clients.status.online': 'Online',
    'admin.clients.status.offline': 'Offline',
    'admin.clients.verified.yes': 'Ja',
    'admin.clients.verified.no': 'Nein',
    'admin.clients.active.active': 'Aktiv',
    'admin.clients.active.blocked': 'Gesperrt',

    // Admin KYC
    'admin.kyc.title': 'KYC-Verifizierung',
    'admin.kyc.subtitle': 'Verifizierungsanfragen verwalten',
    'admin.kyc.loading': 'Wird geladen...',
    'admin.kyc.error': 'Fehler',
    'admin.kyc.networkError': 'Netzwerkfehler',
    'admin.kyc.loadError': 'Anfragen konnten nicht geladen werden',
    'admin.kyc.status.all': 'Alle',
    'admin.kyc.status.draft': 'Entwurf',
    'admin.kyc.status.pending': 'Ausstehend',
    'admin.kyc.status.approved': 'Genehmigt',
    'admin.kyc.status.rejected': 'Abgelehnt',
    'admin.kyc.status.resubmit': 'Erneute Einreichung erforderlich',
    'admin.kyc.review': 'Prüfen',
    'admin.kyc.submitReview': 'Entscheidung absenden',
    'admin.kyc.submitting': 'Wird gesendet...',
    'admin.kyc.reviewSuccess': 'Entscheidung gesendet',
    'admin.kyc.reviewError': 'Fehler beim Senden der Entscheidung',
    'admin.kyc.selectStatus': 'Status auswählen',
    'admin.kyc.notes': 'Kommentare',
    'admin.kyc.notesPlaceholder': 'Kommentare eingeben (optional)',
    'admin.kyc.cancel': 'Abbrechen',
    'admin.kyc.client': 'Kunde',
    'admin.kyc.submitted': 'Eingereicht',
    'admin.kyc.reviewed': 'Geprüft',
    'admin.kyc.noRequests': 'Keine Anfragen',

    // Admin Pairs
    'admin.pairs.title': 'Handelspaare',
    'admin.pairs.subtitle': 'Handelspaare verwalten',
    'admin.pairs.loading': 'Wird geladen...',
    'admin.pairs.refresh': 'Aktualisieren',
    'admin.pairs.import': 'Massenimport',
    'admin.pairs.add': 'Paar hinzufügen',
    'admin.pairs.edit': 'Bearbeiten',
    'admin.pairs.delete': 'Löschen',
    'admin.pairs.symbol': 'Symbol',
    'admin.pairs.name': 'Name',
    'admin.pairs.type': 'Typ',
    'admin.pairs.market': 'Markt',
    'admin.pairs.minQty': 'Min. Menge',
    'admin.pairs.qtyStep': 'Mengenschritt',
    'admin.pairs.priceStep': 'Preisschritt',
    'admin.pairs.leverage': 'Hebel',
    'admin.pairs.mmr': 'MMR',
    'admin.pairs.feeTaker': 'Taker-Gebühr',
    'admin.pairs.feeMaker': 'Maker-Gebühr',
    'admin.pairs.markPriceSource': 'Marktpreisquelle',
    'admin.pairs.created': 'Erstellt',
    'admin.pairs.updated': 'Aktualisiert',
    'admin.pairs.noPairs': 'Keine Handelspaare',

    // Admin Transactions
    'admin.transactions.title': 'Transaktionen',
    'admin.transactions.subtitle': 'Verlauf aller Systemtransaktionen',

    // Admin Withdrawals
    'admin.withdrawals.title': 'Auszahlungen',
    'admin.withdrawals.subtitle': 'Auszahlungsanfragen verwalten',

    // Admin Client Details
    'admin.clientDetails.back': 'Zurück zur Liste',
    'admin.clientDetails.loading': 'Wird geladen...',
    'admin.clientDetails.save': 'Speichern',
    'admin.clientDetails.saving': 'Wird gespeichert...',
    'admin.clientDetails.saved': 'Änderungen gespeichert',
    'admin.clientDetails.saveError': 'Fehler beim Speichern',
    'admin.clientDetails.tabs.profile': 'Profil',
    'admin.clientDetails.tabs.accounts': 'Konten',
    'admin.clientDetails.tabs.deals': 'Trades',
    'admin.clientDetails.tabs.wallets': 'Brieftaschen',
    'admin.clientDetails.profile.title': 'Kundenprofil',
    'admin.clientDetails.profile.name': 'Name',
    'admin.clientDetails.profile.email': 'E-Mail',
    'admin.clientDetails.profile.phone': 'Telefon',
    'admin.clientDetails.profile.password': 'Passwort',
    'admin.clientDetails.profile.emailVerified': 'E-Mail verifiziert',
    'admin.clientDetails.profile.isActive': 'Aktiv',
    'admin.clientDetails.profile.accessLevel': 'Zugriffsebene',
    'admin.clientDetails.profile.accessLevelBase': 'Basis',
    'admin.clientDetails.profile.accessLevelFull': 'Voll',
    'admin.clientDetails.profile.depositRequired': 'Erforderliche Einzahlung',
    'admin.clientDetails.accounts.title': 'Kundenkonten',
    'admin.clientDetails.accounts.demoTopup': 'Demo-Konto aufladen',
    'admin.clientDetails.accounts.demoTopupDesc': 'Schnelle Demo-Guthaben-Aufladung für Kunden',
    'admin.clientDetails.accounts.topupAmount': 'Aufladebetrag ($)',
    'admin.clientDetails.accounts.topup': 'Aufladen',
    'admin.clientDetails.accounts.toppingUp': 'Wird aufgeladen...',
    'admin.clientDetails.accounts.topupHint': 'Aufladung gilt für das erste gefundene Demo-Konto. Wenn kein Demo-Konto existiert, wird es automatisch erstellt.',
    'admin.clientDetails.accounts.financial': 'Finanzkonten',
    'admin.clientDetails.accounts.trading': 'Handelskonten',
    'admin.clientDetails.accounts.noAccounts': 'Keine Konten',
    'admin.clientDetails.deals.title': 'Kundentrades',
    'admin.clientDetails.deals.loading': 'Trades werden geladen...',
    'admin.clientDetails.deals.noDeals': 'Keine Trades',
    'admin.clientDetails.wallets.title': 'Kundenbrieftaschen',
    'admin.clientDetails.wallets.loading': 'Brieftaschen werden geladen...',
    'admin.clientDetails.wallets.noWallets': 'Keine Brieftaschen',
    'admin.clientDetails.wallets.create': 'Brieftasche erstellen',
    'admin.clientDetails.wallets.type': 'Typ',
    'admin.clientDetails.wallets.address': 'Adresse',
    'admin.clientDetails.wallets.created': 'Erstellt',

    // Portfolio
    'portfolio.title': 'Portfolio',
    'portfolio.all': 'Alle Trades',
    'portfolio.open': 'Offene',
    'portfolio.closed': 'Geschlossene',
    'portfolio.totalTrades': 'Gesamtanzahl Trades',
    'portfolio.openCount': 'Offene',
    'portfolio.realizedPnl': 'Realisierter PnL',
    'portfolio.unrealizedPnl': 'Nicht realisierter PnL',
    'portfolio.trades': 'Trades',
    'portfolio.noDeals': 'Keine Trades',
    'portfolio.loading': 'Wird geladen...',
    'portfolio.tradeOpen': 'Offen',
    'portfolio.tradeClosed': 'Geschlossen',
    'portfolio.long': 'Long',
    'portfolio.short': 'Short',

    // Messages
    'messages.support': 'Support',
    'messages.yourTickets': 'Ihre Anfragen',
    'messages.new': 'Neue Anfrage',
    'messages.subject': 'Betreff',
    'messages.subjectPlaceholder': 'Beschreiben Sie kurz das Problem',
    'messages.priority': 'Priorität',
    'messages.message': 'Nachricht',
    'messages.messagePlaceholder': 'Beschreiben Sie Ihr Problem ausführlich',
    'messages.writeMessage': 'Nachricht schreiben...',
    'messages.create': 'Anfrage erstellen',
    'messages.cancel': 'Abbrechen',
    'messages.noTickets': 'Noch keine Anfragen',
    'messages.selectOrCreate': 'Wählen Sie eine Anfrage oder erstellen Sie eine neue',
    'messages.loadingTickets': 'Anfragen werden geladen...',
    'messages.loadingDetails': 'Details werden geladen...',
    'messages.low': 'Niedrig',
    'messages.medium': 'Mittel',
    'messages.high': 'Hoch',
    'messages.urgent': 'Dringend',

    // Positions accordion
    'positions.openTrades': 'Offene Trades',
    'positions.collapse': 'Einklappen',
    'positions.expand': 'Ausklappen',
    'positions.noOpen': 'Keine offenen Trades',
    'positions.marginLocked': 'Gesperrte Marge',
    'positions.tradeDetails': 'Trade-Details',
    'positions.openPosition': 'Offene Position',
    'positions.closedPosition': 'Geschlossene Position',
    'positions.id': 'Trade-ID',
    'positions.status': 'Status',
    'positions.type': 'Typ',
    'positions.entryPrice': 'Einstiegspreis',
    'positions.leverage': 'Hebel',
    'positions.mode': 'Modus',
    'positions.qty': 'Volumen',
    'positions.createdAt': 'Erstellt am',
    'positions.updatedAt': 'Aktualisiert am',
    'positions.liqPrice': 'Liquidationspreis',
    'positions.markPrice': 'Mark-Preis',
    'positions.currentPnl': 'Aktueller PnL',
    'positions.roe': 'ROE (%)',
    'positions.closing': 'Schließen...',
    'positions.closePosition': 'Position schließen',

    // Trading panel
    'trade.buy': 'Kaufen',
    'trade.sell': 'Verkaufen',
    'trade.maintenanceMargin': 'Erhaltungsmarge',
    'trade.initialMargin': 'Anfangsmarge',
    'trade.highRisk': 'Hohes Risiko',
    'trade.required': 'Erforderlich',
    'trade.tradingBlocked': 'Handel gesperrt',
    'trade.fullAccessRequired': 'Voller Zugriff erforderlich',
    'trade.notAllowedForSymbol': 'Für dieses Symbol nicht verfügbar',
    'common.unavailable': 'nicht verfügbar',
    'pairs.search': 'Paar suchen',
    'pairs.nothingFound': 'Nichts gefunden',
    'pairs.favorites': 'Favoriten',

    // Accounts
    'accounts.tabs.accounts': 'Konten',
    'accounts.tabs.deposit': 'Einzahlen',
    'accounts.tabs.transfer': 'Überweisen',
    'accounts.tabs.history': 'Verlauf',
    'accounts.financialAccounts': 'Finanzkonten',
    'accounts.tradingAccounts': 'Handelskonten',
    'accounts.transfer': 'Überweisen',
    'accounts.deposit': 'Einzahlen',
    'accounts.otherWallets': 'Andere Wallets',
    'accounts.liveAccount': 'LIVE-Konto',
    'accounts.demoAccount': 'DEMO-Konto',
    'accounts.history.title': 'Zahlungshistorie:',
    'accounts.history.subtitle': 'Hier sehen Sie Ihre Ein- und Auszahlungen',
    'accounts.history.id': 'ID',
    'accounts.history.date': 'Datum',
    'accounts.history.operation': 'Vorgang',
    'accounts.history.amount': 'Betrag',
    'accounts.history.download': 'Historie herunterladen',
    'accounts.deposit.title': 'Aufladen des Finanzkontos:',
    'accounts.deposit.subtitle': 'Wir beeinflussen die Bearbeitungszeit nicht. Bei Problemen wenden Sie sich an den Support',
    'accounts.deposit.notice': 'Achtung! Mindestbetrag 100 USD',
    'accounts.deposit.to': 'Wohin:',
    'accounts.deposit.amountToSend': 'Zu sendender Betrag:',
    'accounts.deposit.usdEquivalent': 'US-Dollar Gegenwert:',
    'accounts.deposit.submit': 'Einzahlen',
    'accounts.transfer.title': 'Überweisung zwischen Konten:',
    'accounts.transfer.from': 'Von:',
    'accounts.transfer.to': 'Nach:',
    'accounts.transfer.amount': 'Überweisungsbetrag:',
    'accounts.transfer.creditAmount': 'Gutschriftbetrag:',
    'accounts.transfer.submit': 'Überweisen',

    // Deposit Ticket
    'depositTicket.title': 'Einzahlung',
    'depositTicket.description': 'Senden Sie Kryptowährung an die angegebene Adresse',
    'depositTicket.status.completed': 'Abgeschlossen',
    'depositTicket.status.pending': 'Ausstehend',
    'depositTicket.status.expired': 'Abgelaufen',
    'depositTicket.status.failed': 'Fehler',
    'depositTicket.loading': 'Wird geladen...',
    'depositTicket.notFound': 'Ticket nicht gefunden',
    'depositTicket.backToDeposit': 'Zurück zur Einzahlung',
    'depositTicket.completed.title': 'Mittel erhalten!',
    'depositTicket.completed.description': 'Ihr Guthaben wurde erfolgreich aktualisiert',
    'depositTicket.completed.txId': 'Transaktions-ID',
    'depositTicket.completed.backToAccounts': 'Zurück zu Konten',
    'depositTicket.expired.title': 'Zeit abgelaufen',
    'depositTicket.expired.description': 'Erstellen Sie ein neues Ticket für die Einzahlung',
    'depositTicket.expired.createNew': 'Neues Ticket erstellen',
    'depositTicket.failed.title': 'Einzahlungsfehler',
    'depositTicket.failed.description': 'Einzahlung fehlgeschlagen. Bitte kontaktieren Sie den Support.',
    'depositTicket.timeRemaining': 'Verbleibende Zeit',
    'depositTicket.amountInUSD': 'Betrag in USD',
    'depositTicket.amountIn': 'Betrag in',
    'depositTicket.rate': 'Kurs',
    'depositTicket.loadingRate': 'Kurs wird geladen...',
    'depositTicket.address': 'Einzahlungsadresse',
    'depositTicket.copy': 'Kopieren',
    'depositTicket.copied': 'Adresse kopiert!',
    'depositTicket.info.ticket': 'Ticket',
    'depositTicket.info.sendOnly': 'Senden Sie nur',
    'depositTicket.info.onThisAddress': 'an diese Adresse',
    'depositTicket.info.confirmation': 'Die Gutschrift erfolgt nach Bestätigung des Netzwerks (normalerweise 1-3 Minuten)',
    'depositTicket.info.autoCheck': 'Der Status wird automatisch alle 10 Sekunden überprüft',

    // Profile
    'profile.tabs.info': 'Persönliche Daten',
    'profile.tabs.verification': 'Verifizierung',
    'profile.tabs.twofa': 'Zwei-Faktor-Authentifizierung',
    'profile.tabs.password': 'Passwort ändern',
    'profile.loading': 'Profil wird geladen...',
    'profile.name': 'Name',
    'profile.surname': 'Nachname',
    'profile.gender': 'Geschlecht',
    'profile.dob': 'Geburtsdatum',
    'profile.country': 'Land',
    'profile.city': 'Stadt',
    'profile.address': 'Adresse',
    'profile.postcode': 'Postleitzahl',
    'profile.email': 'E-Mail',
    'profile.phone': 'Telefon',
    'profile.gender.male': 'Männlich',
    'profile.gender.female': 'Weiblich',

    'profile.tabs.mobile.info': 'Persönliche Daten',
    'profile.tabs.mobile.verification': 'Verifizierung',
    'profile.tabs.mobile.2fa': 'Zwei-Faktor-Authentifizierung',
    'profile.tabs.mobile.password': 'Passwort ändern',
    'profile.loadError.title': 'Profil konnte nicht geladen werden',
    'profile.loadError.desc': 'Aktualisieren Sie die Seite und versuchen Sie es erneut',
    'profile.imageSaveError.title': 'Foto konnte nicht gespeichert werden',
    'profile.imageSaveError.desc': 'Bitte später erneut versuchen',
    'profile.photoUpdated.title': 'Profilfoto aktualisiert!',
    'profile.photoUpdated.desc': 'Änderungen wurden gespeichert',
    'profile.photoRemoved.title': 'Profilfoto entfernt!',
    'profile.photoRemoved.desc': 'Änderungen wurden gespeichert',
    'profile.saveSuccess.title': 'Profil gespeichert!',
    'profile.saveSuccess.desc': 'Alle Änderungen wurden gespeichert',
    'profile.saveFailed.title': 'Profil konnte nicht gespeichert werden',
    'profile.saveFailed.desc': 'Überprüfen Sie die Daten und versuchen Sie es erneut',
    'profile.networkError.title': 'Netzwerkfehler',
    'profile.networkError.desc': 'Vorgang fehlgeschlagen. Bitte erneut versuchen',
    'profile.verif.loading': 'Verifizierungsdaten werden geladen...',
    'profile.verif.status': 'Verifizierungsstatus:',
    'profile.verif.identityVerified': '✅ Ihre Identität wurde erfolgreich verifiziert!',
    'profile.verif.rejected': '❌ Verifizierung abgelehnt. Laden Sie neue Dokumente hoch und versuchen Sie es erneut.',
    'profile.verif.pending': '⏳ Dokumente werden geprüft. Wir benachrichtigen in 24–48 Stunden.',
    'profile.verif.pendingNote': 'Die Dokumente wurden zur Prüfung eingereicht. Wir informieren Sie per E-Mail.',
    'profile.verif.approvedNote': 'Die Dokumente wurden erfolgreich verifiziert.',
    'profile.verif.instructions': 'Bitte laden Sie klare Fotos Ihres amtlichen Ausweises hoch (Pass, Führerschein usw.)',
    'profile.verif.frontTitle': 'Vorderseite des Dokuments',
    'profile.verif.frontDesc': 'Laden Sie die Vorderseite hoch. Der Text muss gut lesbar sein.',
    'profile.verif.backTitle': 'Rückseite / Selfie',
    'profile.verif.backDesc': 'Laden Sie die Rückseite oder ein Selfie mit dem Dokument hoch.',
    'profile.verif.submit': 'Zur Prüfung einreichen',
    'profile.verif.submitting': 'Wird gesendet...',
    'profile.verif.lastSubmitted': 'Zuletzt eingereicht:',
    'profile.verif.notAuthorized.title': 'Nicht autorisiert',
    'profile.verif.notAuthorized.desc': 'Melden Sie sich an, um Dokumente hochzuladen',
    'profile.verif.saveDocError.title': 'Dokument konnte nicht gespeichert werden',
    'profile.verif.saveDocError.desc': 'Bitte später erneut versuchen',
    'profile.verif.docSaved.title': 'Dokument gespeichert!',
    'profile.verif.docSaved.uploaded': 'Dokument erfolgreich hochgeladen',
    'profile.verif.docSaved.removed': 'Dokument erfolgreich entfernt',
    'profile.verif.docsRequired.title': 'Dokumente erforderlich',
    'profile.verif.docsRequired.desc': 'Laden Sie Vorder- und Rückseite hoch',
    'profile.verif.submitFailed.title': 'Senden fehlgeschlagen',
    'profile.verif.submitFailed.desc': 'Dokumente konnten nicht gesendet werden. Bitte erneut versuchen',
    'profile.2fa.loading': '2FA wird geladen...',
    'profile.2fa.recommend': 'Wir empfehlen, 2FA zu aktivieren, um Ihr Konto zu schützen.',
    'profile.2fa.enabled': '2FA aktiviert',
    'profile.2fa.disabled': '2FA deaktiviert',
    'profile.2fa.setup': '2FA einrichten',
    'profile.2fa.preparing': 'Vorbereitung...',
    'profile.2fa.disable': '2FA deaktivieren',
    'profile.2fa.disabling': 'Wird deaktiviert...',
    'profile.2fa.scanQr': 'Scannen Sie diesen QR-Code in Google Authenticator oder geben Sie das Geheimnis manuell ein.',
    'profile.2fa.openOtpauth': 'otpauth-Link öffnen',
    'profile.2fa.secret': 'Geheimnis:',
    'profile.2fa.enterCode': '6-stelligen Code eingeben',
    'profile.2fa.verify': 'Bestätigen',
    'profile.2fa.verifying': 'Wird überprüft...',
    'profile.password.old': 'Altes Passwort:',
    'profile.password.new': 'Neues Passwort:',
    'profile.password.repeat': 'Neues Passwort wiederholen:',
    'profile.password.help': 'Wenn Sie das alte Passwort nicht wissen, kontaktieren Sie bitte den Support',
    'profile.password.change': 'Ändern',
  },
  en: {
    // Auth pages
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.accountRegistration': 'Account registration',
    'auth.passwordRecovery': 'Password recovery',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.name': 'Name',
    'auth.surname': 'Surname',
    'auth.phone': 'Phone number',
    'auth.enterPhoneNumber': 'Enter a phone number',
    'auth.repeatPassword': 'Repeat password',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.signIn': 'Sign in',
    'auth.signUp': 'Sign up',
    'auth.alreadyHaveAccount': 'Already have an account?',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.continue': 'Continue',
    'auth.backToLogin': 'Back to login',
    'auth.byRegisteringAccept': 'By registering, I accept',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.detectingCountry': 'Detecting country...',
    'auth.detected': 'Detected',
    'auth.createAccountDescription': 'Create a new account to get started',
    'auth.loginDescription': 'Sign in to your account',
    'auth.forgotPasswordDescription': 'Enter email for password recovery',
    
    // Email verification
    'auth.verifyEmail': 'Verify email',
    'auth.verifyEmailDescription': 'We sent a confirmation link to your email',
    'auth.checkYourEmail': 'Check your email',
    'auth.emailSent': 'Email sent!',
    'auth.verificationSent': 'We sent a confirmation email to {email}',
    'auth.verificationInstructions': 'Click the link in the email to activate your account',
    'auth.checkEmailInstructions': 'Check {email} and click the confirmation link',
    'auth.resendEmail': 'Resend email',
    'auth.didntReceiveEmail': 'Didn\'t receive the email?',
    'auth.checkSpamFolder': 'Check your spam folder',
    'auth.verificationError': 'Error sending email',
    'auth.emailNotVerified': 'Email not verified. Check your email and confirm registration',
    'auth.alreadyRegistered': 'Account with this email already registered. Check your email for confirmation',
    
    // Validation messages
    'validation.passwordsNotMatch': 'Passwords do not match',
    'validation.passwordMinLength': 'Password must be at least 6 characters',
    'validation.invalidPhoneFormat': 'Invalid phone number format',
    'validation.acceptPrivacy': 'You must accept the Privacy Policy',
    'validation.allFieldsRequired': 'All fields are required',
    'validation.userExists': 'User with this email already exists',
    'validation.invalidCredentials': 'Invalid email or password',
    'validation.registrationSuccess': 'Registration successful! Now sign in.',
    'validation.registrationError': 'An error occurred during registration',
    'validation.loginError': 'An error occurred during login',
    'validation.passwordResetSent': 'If an account with this email exists, password recovery instructions have been sent to your email',
    'validation.emailRequired': 'Email is required',
    'validation.passwordRequired': 'Password is required',
    'validation.nameRequired': 'Name is required',
    'validation.surnameRequired': 'Surname is required',
    'validation.phoneRequired': 'Phone number is required',
    'validation.invalidEmail': 'Please enter a valid email',
    'validation.passwordTooShort': 'Password is too short',
    'validation.passwordTooLong': 'Password is too long',
    'validation.nameTooShort': 'Name is too short',
    'validation.nameTooLong': 'Name is too long',
    
    // Dashboard
    'dashboard.hello': 'Hello',
    'dashboard.portfolio': 'Portfolio',
    'dashboard.transactions': 'Transactions',
    'dashboard.analytics': 'Analytics',
    'dashboard.totalValue': 'Total value',
    'dashboard.totalOperations': 'Total operations',
    'dashboard.profitability': 'Profitability',
    'dashboard.logout': 'Logout',
    'dashboard.manageInvestments': 'Manage your investments',
    'dashboard.operationHistory': 'Your operation history',
    'dashboard.statisticsReports': 'Statistics and reports',
    
    // Common
    'common.loading': 'Loading...',
    'common.signingIn': 'Signing in...',
    'common.registering': 'Registering...',
    'common.sending': 'Sending...',
    'common.uploadPhoto': 'Upload Photo',
    'common.changePhoto': 'Change Photo',
    'common.remove': 'Remove',
    'common.photoHint': 'JPEG, PNG, GIF or WebP (max 5MB)',
    'common.uploadDocument': 'Upload Document',
    'common.changeDocument': 'Change Document',
    'common.uploadDocumentPlaceholder': 'Click to upload document',
    'common.save': 'Save',
    'common.cancel': 'Cancel',

    // Header
    'header.funds': 'Funds',
    'header.available': 'Available',
    'header.margin': 'Margin',
    'header.profit': 'Profit',
    'header.kyiv': 'Moscow',
    'header.details': 'Details',
    'header.profile': 'Profile',
    'header.logout': 'Logout',

    // Nav
    'nav.assets': 'Assets',
    'nav.accounts': 'Accounts',
    'nav.support': 'Support',
    'nav.profile': 'Profile',

    // Logout dialog
    'common.confirmLogout': 'Confirm logout',
    'common.logoutConfirmMessage': 'Are you sure you want to log out?',
    'common.logout': 'Logout',

    // Admin dashboard
    'admin.dashboardTitle': 'Admin dashboard',
    'admin.dashboardSubtitle': 'Overview of key metrics and statistics',
    'admin.clientsToday': 'Clients today',
    'admin.newRegistrationsToday': 'New registrations today',
    'admin.profit': 'Profit',
    'admin.totalProfit': 'Total system profit',
    'admin.metricPlaceholderTitle': 'Metric',
    'admin.metricPlaceholderHint': 'Placeholder for your metric',
    'admin.chart2': 'Chart 2',
    'admin.chart3': 'Chart 3',
    'admin.chartPlaceholder': 'Chart will be here',
    'admin.clientsPeriod': 'Clients over period',
    'admin.totalClients': 'Total clients',
    'admin.selectPeriod': 'Select period',
    'admin.last3months': 'Last 3 months',
    'admin.last30days': 'Last 30 days',
    'admin.last7days': 'Last 7 days',
    // Admin sidebar
    'admin.sidebar.title': 'Admin panel',
    'admin.sidebar.dashboard': 'Dashboard',
    'admin.sidebar.clients': 'Clients',
    'admin.sidebar.pairs': 'Pairs',
    'admin.sidebar.kyc': 'KYC',
    'admin.sidebar.tickets': 'Tickets',
    'admin.sidebar.transactions': 'Transactions',
    'admin.sidebar.withdrawals': 'Withdrawals',
    'admin.sidebar.deals': 'Deals',
    'admin.sidebar.admins': 'Admins',
    'admin.sidebar.settings': 'Settings',
    'admin.sidebar.settingsGeneral': 'General',
    'admin.sidebar.settingsSecurity': 'Security',

    // Admin Tickets
    'admin.tickets.title': 'Support Tickets',
    'admin.tickets.subtitle': 'Manage client tickets',
    'admin.tickets.loading': 'Loading tickets...',
    'admin.tickets.list': 'Ticket List',
    'admin.tickets.noTickets': 'No tickets',
    'admin.tickets.selectTicket': 'Select a ticket to view',
    'admin.tickets.client': 'Client',
    'admin.tickets.support': 'Support',
    'admin.tickets.writeReply': 'Write a reply...',
    'admin.tickets.replySent': 'Reply sent',
    'admin.tickets.statusUpdated': 'Status updated',
    'admin.tickets.messageUpdated': 'Message updated',
    'admin.tickets.error': 'Error',
    'admin.tickets.updateError': 'Failed to update message',
    'admin.tickets.updateErrorDesc': 'An error occurred while updating the message',
    'admin.tickets.editMessage': 'Edit message',
    'admin.tickets.save': 'Save',
    'admin.tickets.saving': 'Saving...',
    'admin.tickets.cancel': 'Cancel',
    'admin.tickets.saveHint': 'Ctrl+Enter to save, Esc to cancel',
    'admin.tickets.status.all': 'All',
    'admin.tickets.status.open': 'Open',
    'admin.tickets.status.inProgress': 'In Progress',
    'admin.tickets.status.awaitingReply': 'Awaiting Reply',
    'admin.tickets.status.resolved': 'Resolved',
    'admin.tickets.status.closed': 'Closed',
    'admin.tickets.status.openSingle': 'Open',
    'admin.tickets.status.inProgressSingle': 'In Progress',
    'admin.tickets.status.awaitingReplySingle': 'Awaiting Reply',
    'admin.tickets.status.resolvedSingle': 'Resolved',
    'admin.tickets.status.closedSingle': 'Closed',

    // Admin Clients
    'admin.clients.title': 'Clients',
    'admin.clients.subtitle': 'Manage system clients',
    'admin.clients.delete': 'Delete',
    'admin.clients.deleteSelected': 'Delete ({count})',
    'admin.clients.export': 'Export CSV',
    'admin.clients.exporting': 'Exporting...',
    'admin.clients.addClient': 'Add Client',
    'admin.clients.list': 'Client List',
    'admin.clients.resetFilters': 'Reset Filters',
    'admin.clients.searchByName': 'Search by name...',
    'admin.clients.searchByEmail': 'Search by email...',
    'admin.clients.searchByPhone': 'Search by phone...',
    'admin.clients.verification': 'Verification',
    'admin.clients.verificationAll': 'All',
    'admin.clients.verificationYes': 'Verified',
    'admin.clients.verificationNo': 'Not Verified',
    'admin.clients.loading': 'Loading...',
    'admin.clients.noClients': 'No clients',
    'admin.clients.shown': 'Showing {shown} of {total} clients',
    'admin.clients.page': 'Page {current} of {total}',
    'admin.clients.prev': 'Previous',
    'admin.clients.next': 'Next',
    'admin.clients.create': 'Create Client',
    'admin.clients.createDesc': 'Add a new client to the system',
    'admin.clients.edit': 'Edit Client',
    'admin.clients.editDesc': 'Modify client data',
    'admin.clients.deleteConfirm': 'Delete Client',
    'admin.clients.deleteConfirmDesc': 'Are you sure you want to delete client {email}? This action cannot be undone.',
    'admin.clients.name': 'Name',
    'admin.clients.email': 'Email',
    'admin.clients.password': 'Password',
    'admin.clients.passwordNew': 'New password (leave empty to keep current)',
    'admin.clients.phone': 'Phone',
    'admin.clients.emailVerified': 'Email verified',
    'admin.clients.createButton': 'Create',
    'admin.clients.saveButton': 'Save',
    'admin.clients.deleteButton': 'Delete',
    'admin.clients.generatePassword': 'Generate password',
    'admin.clients.createError': 'Error creating client',
    'admin.clients.updateError': 'Error updating client',
    'admin.clients.deleteError': 'Error deleting client',
    'admin.clients.exportError': 'Failed to export',
    'admin.clients.bulkDeleteConfirm': 'Delete {count} client(s)?',
    'admin.clients.bulkDeleteError': 'Error deleting',
    'admin.clients.columns.status': 'Status',
    'admin.clients.columns.name': 'Name',
    'admin.clients.columns.email': 'Email',
    'admin.clients.columns.phone': 'Phone',
    'admin.clients.columns.wallets': 'Wallets',
    'admin.clients.columns.accounts': 'Accounts',
    'admin.clients.columns.balance': 'Balance',
    'admin.clients.columns.verified': 'Verified',
    'admin.clients.columns.active': 'Active',
    'admin.clients.columns.created': 'Created',
    'admin.clients.columns.actions': 'Actions',
    'admin.clients.status.online': 'Online',
    'admin.clients.status.offline': 'Offline',
    'admin.clients.verified.yes': 'Yes',
    'admin.clients.verified.no': 'No',
    'admin.clients.active.active': 'Active',
    'admin.clients.active.blocked': 'Blocked',

    // Admin KYC
    'admin.kyc.title': 'KYC Verification',
    'admin.kyc.subtitle': 'Manage verification requests',
    'admin.kyc.loading': 'Loading...',
    'admin.kyc.error': 'Error',
    'admin.kyc.networkError': 'Network Error',
    'admin.kyc.loadError': 'Failed to load requests',
    'admin.kyc.status.all': 'All',
    'admin.kyc.status.draft': 'Draft',
    'admin.kyc.status.pending': 'Pending',
    'admin.kyc.status.approved': 'Approved',
    'admin.kyc.status.rejected': 'Rejected',
    'admin.kyc.status.resubmit': 'Resubmit Required',
    'admin.kyc.review': 'Review',
    'admin.kyc.submitReview': 'Submit Decision',
    'admin.kyc.submitting': 'Submitting...',
    'admin.kyc.reviewSuccess': 'Decision submitted',
    'admin.kyc.reviewError': 'Error submitting decision',
    'admin.kyc.selectStatus': 'Select status',
    'admin.kyc.notes': 'Comments',
    'admin.kyc.notesPlaceholder': 'Enter comments (optional)',
    'admin.kyc.cancel': 'Cancel',
    'admin.kyc.client': 'Client',
    'admin.kyc.submitted': 'Submitted',
    'admin.kyc.reviewed': 'Reviewed',
    'admin.kyc.noRequests': 'No requests',

    // Admin Pairs
    'admin.pairs.title': 'Trading Pairs',
    'admin.pairs.subtitle': 'Manage trading pairs',
    'admin.pairs.loading': 'Loading...',
    'admin.pairs.refresh': 'Refresh',
    'admin.pairs.import': 'Bulk Import',
    'admin.pairs.add': 'Add Pair',
    'admin.pairs.edit': 'Edit',
    'admin.pairs.delete': 'Delete',
    'admin.pairs.symbol': 'Symbol',
    'admin.pairs.name': 'Name',
    'admin.pairs.type': 'Type',
    'admin.pairs.market': 'Market',
    'admin.pairs.minQty': 'Min Qty',
    'admin.pairs.qtyStep': 'Qty Step',
    'admin.pairs.priceStep': 'Price Step',
    'admin.pairs.leverage': 'Leverage',
    'admin.pairs.mmr': 'MMR',
    'admin.pairs.feeTaker': 'Taker Fee',
    'admin.pairs.feeMaker': 'Maker Fee',
    'admin.pairs.markPriceSource': 'Mark Price Source',
    'admin.pairs.created': 'Created',
    'admin.pairs.updated': 'Updated',
    'admin.pairs.noPairs': 'No trading pairs',

    // Admin Transactions
    'admin.transactions.title': 'Transactions',
    'admin.transactions.subtitle': 'History of all system transactions',

    // Admin Withdrawals
    'admin.withdrawals.title': 'Withdrawals',
    'admin.withdrawals.subtitle': 'Manage withdrawal requests',

    // Admin Client Details
    'admin.clientDetails.back': 'Back to List',
    'admin.clientDetails.loading': 'Loading...',
    'admin.clientDetails.save': 'Save',
    'admin.clientDetails.saving': 'Saving...',
    'admin.clientDetails.saved': 'Changes saved',
    'admin.clientDetails.saveError': 'Error saving',
    'admin.clientDetails.tabs.profile': 'Profile',
    'admin.clientDetails.tabs.accounts': 'Accounts',
    'admin.clientDetails.tabs.deals': 'Deals',
    'admin.clientDetails.tabs.wallets': 'Wallets',
    'admin.clientDetails.profile.title': 'Client Profile',
    'admin.clientDetails.profile.name': 'Name',
    'admin.clientDetails.profile.email': 'Email',
    'admin.clientDetails.profile.phone': 'Phone',
    'admin.clientDetails.profile.password': 'Password',
    'admin.clientDetails.profile.emailVerified': 'Email verified',
    'admin.clientDetails.profile.isActive': 'Active',
    'admin.clientDetails.profile.accessLevel': 'Access Level',
    'admin.clientDetails.profile.accessLevelBase': 'Base',
    'admin.clientDetails.profile.accessLevelFull': 'Full',
    'admin.clientDetails.profile.depositRequired': 'Required Deposit',
    'admin.clientDetails.accounts.title': 'Client Accounts',
    'admin.clientDetails.accounts.demoTopup': 'Demo Account Top-up',
    'admin.clientDetails.accounts.demoTopupDesc': 'Quick demo balance top-up for client',
    'admin.clientDetails.accounts.topupAmount': 'Top-up Amount ($)',
    'admin.clientDetails.accounts.topup': 'Top-up',
    'admin.clientDetails.accounts.toppingUp': 'Topping up...',
    'admin.clientDetails.accounts.topupHint': 'Top-up applies to the first found demo account. If no demo account exists, it will be created automatically.',
    'admin.clientDetails.accounts.financial': 'Financial Accounts',
    'admin.clientDetails.accounts.trading': 'Trading Accounts',
    'admin.clientDetails.accounts.noAccounts': 'No accounts',
    'admin.clientDetails.deals.title': 'Client Deals',
    'admin.clientDetails.deals.loading': 'Loading deals...',
    'admin.clientDetails.deals.noDeals': 'No deals',
    'admin.clientDetails.wallets.title': 'Client Wallets',
    'admin.clientDetails.wallets.loading': 'Loading wallets...',
    'admin.clientDetails.wallets.noWallets': 'No wallets',
    'admin.clientDetails.wallets.create': 'Create Wallet',
    'admin.clientDetails.wallets.type': 'Type',
    'admin.clientDetails.wallets.address': 'Address',
    'admin.clientDetails.wallets.created': 'Created',

    // Portfolio
    'portfolio.title': 'Portfolio',
    'portfolio.all': 'All trades',
    'portfolio.open': 'Open',
    'portfolio.closed': 'Closed',
    'portfolio.totalTrades': 'Total trades',
    'portfolio.openCount': 'Open',
    'portfolio.realizedPnl': 'Realized PnL',
    'portfolio.unrealizedPnl': 'Unrealized PnL',
    'portfolio.trades': 'Trades',
    'portfolio.noDeals': 'No trades',
    'portfolio.loading': 'Loading...',
    'portfolio.tradeOpen': 'Open',
    'portfolio.tradeClosed': 'Closed',
    'portfolio.long': 'Long',
    'portfolio.short': 'Short',

    // Messages
    'messages.support': 'Support',
    'messages.yourTickets': 'Your tickets',
    'messages.new': 'New ticket',
    'messages.subject': 'Subject',
    'messages.subjectPlaceholder': 'Briefly describe the problem',
    'messages.priority': 'Priority',
    'messages.message': 'Message',
    'messages.messagePlaceholder': 'Describe your problem in detail',
    'messages.writeMessage': 'Write a message...',
    'messages.create': 'Create ticket',
    'messages.cancel': 'Cancel',
    'messages.noTickets': 'You have no tickets yet',
    'messages.selectOrCreate': 'Select a ticket or create a new one',
    'messages.loadingTickets': 'Loading tickets...',
    'messages.loadingDetails': 'Loading details...',
    'messages.low': 'Low',
    'messages.medium': 'Medium',
    'messages.high': 'High',
    'messages.urgent': 'Urgent',

    // Positions accordion
    'positions.openTrades': 'Open trades',
    'positions.collapse': 'Collapse',
    'positions.expand': 'Expand',
    'positions.noOpen': 'No open trades',
    'positions.marginLocked': 'Margin locked',
    'positions.tradeDetails': 'Trade details',
    'positions.openPosition': 'Open position',
    'positions.closedPosition': 'Closed position',
    'positions.id': 'Trade ID',
    'positions.status': 'Status',
    'positions.type': 'Type',
    'positions.entryPrice': 'Entry price',
    'positions.leverage': 'Leverage',
    'positions.mode': 'Mode',
    'positions.qty': 'Quantity',
    'positions.createdAt': 'Created at',
    'positions.updatedAt': 'Updated at',
    'positions.liqPrice': 'Liquidation',
    'positions.markPrice': 'Mark price',
    'positions.currentPnl': 'Current PnL',
    'positions.roe': 'ROE (%)',
    'positions.closing': 'Closing...',
    'positions.closePosition': 'Close position',

    // Trading panel
    'trade.buy': 'Buy',
    'trade.sell': 'Sell',
    'trade.maintenanceMargin': 'Maintenance margin',
    'trade.initialMargin': 'Initial margin',
    'trade.highRisk': 'High risk',
    'trade.required': 'Required',
    'trade.tradingBlocked': 'Trading is blocked',
    'trade.fullAccessRequired': 'Full access required',
    'trade.notAllowedForSymbol': 'Not allowed for this symbol',
    'common.unavailable': 'unavailable',
    'pairs.search': 'Search pair',
    'pairs.nothingFound': 'Nothing found',
    'pairs.favorites': 'Favorites',

    // Accounts
    'accounts.tabs.accounts': 'Accounts',
    'accounts.tabs.deposit': 'Deposit',
    'accounts.tabs.transfer': 'Transfer',
    'accounts.tabs.history': 'History',
    'accounts.financialAccounts': 'Financial accounts',
    'accounts.tradingAccounts': 'Trading accounts',
    'accounts.transfer': 'Transfer',
    'accounts.deposit': 'Deposit',
    'accounts.otherWallets': 'Other wallets',
    'accounts.liveAccount': 'LIVE account',
    'accounts.demoAccount': 'DEMO account',
    'accounts.history.title': 'Payment history:',
    'accounts.history.subtitle': 'Here you can view your deposits and withdrawals',
    'accounts.history.id': 'ID',
    'accounts.history.date': 'Date',
    'accounts.history.operation': 'Operation',
    'accounts.history.amount': 'Amount',
    'accounts.history.download': 'Download history',
    'accounts.deposit.title': 'Deposit to financial account:',
    'accounts.deposit.subtitle': 'We do not control processing time. If issues arise, contact support',
    'accounts.deposit.notice': 'Attention! Minimum amount is 100 USD',
    'accounts.deposit.to': 'To:',
    'accounts.deposit.amountToSend': 'Amount to send:',
    'accounts.deposit.usdEquivalent': 'USD equivalent:',
    'accounts.deposit.submit': 'Deposit',
    'accounts.transfer.title': 'Transfer between accounts:',
    'accounts.transfer.from': 'From:',
    'accounts.transfer.to': 'To:',
    'accounts.transfer.amount': 'Transfer amount:',
    'accounts.transfer.creditAmount': 'Credit amount:',
    'accounts.transfer.submit': 'Transfer',

    // Deposit Ticket
    'depositTicket.title': 'Deposit',
    'depositTicket.description': 'Send cryptocurrency to the specified address',
    'depositTicket.status.completed': 'Completed',
    'depositTicket.status.pending': 'Pending',
    'depositTicket.status.expired': 'Expired',
    'depositTicket.status.failed': 'Failed',
    'depositTicket.loading': 'Loading...',
    'depositTicket.notFound': 'Ticket not found',
    'depositTicket.backToDeposit': 'Back to deposit',
    'depositTicket.completed.title': 'Funds received!',
    'depositTicket.completed.description': 'Your balance has been successfully updated',
    'depositTicket.completed.txId': 'Transaction ID',
    'depositTicket.completed.backToAccounts': 'Back to accounts',
    'depositTicket.expired.title': 'Time expired',
    'depositTicket.expired.description': 'Create a new ticket to deposit',
    'depositTicket.expired.createNew': 'Create new ticket',
    'depositTicket.failed.title': 'Deposit error',
    'depositTicket.failed.description': 'Deposit failed. Please contact support.',
    'depositTicket.timeRemaining': 'Time remaining',
    'depositTicket.amountInUSD': 'Amount in USD',
    'depositTicket.amountIn': 'Amount in',
    'depositTicket.rate': 'Rate',
    'depositTicket.loadingRate': 'Loading rate...',
    'depositTicket.address': 'Deposit address',
    'depositTicket.copy': 'Copy',
    'depositTicket.copied': 'Address copied!',
    'depositTicket.info.ticket': 'Ticket',
    'depositTicket.info.sendOnly': 'Send only',
    'depositTicket.info.onThisAddress': 'to this address',
    'depositTicket.info.confirmation': 'Crediting will occur after network confirmation (usually 1-3 minutes)',
    'depositTicket.info.autoCheck': 'Status is checked automatically every 10 seconds',

    // Profile
    'profile.tabs.info': 'Personal information',
    'profile.tabs.verification': 'Verification',
    'profile.tabs.twofa': 'Two-factor authentication',
    'profile.tabs.password': 'Change password',
    'profile.loading': 'Loading profile...',
    'profile.name': 'Name',
    'profile.surname': 'Surname',
    'profile.gender': 'Gender',
    'profile.dob': 'Date of Birth',
    'profile.country': 'Country',
    'profile.city': 'City',
    'profile.address': 'Address',
    'profile.postcode': 'Postcode',
    'profile.email': 'Email',
    'profile.phone': 'Phone number',
    'profile.gender.male': 'Male',
    'profile.gender.female': 'Female',

    'profile.tabs.mobile.info': 'Personal information',
    'profile.tabs.mobile.verification': 'Verification',
    'profile.tabs.mobile.2fa': 'Two-factor authentication',
    'profile.tabs.mobile.password': 'Change password',
    'profile.loadError.title': 'Failed to load profile',
    'profile.loadError.desc': 'Refresh the page and try again',
    'profile.imageSaveError.title': 'Failed to save photo',
    'profile.imageSaveError.desc': 'Please try again later',
    'profile.photoUpdated.title': 'Profile photo updated!',
    'profile.photoUpdated.desc': 'Changes saved successfully',
    'profile.photoRemoved.title': 'Profile photo removed!',
    'profile.photoRemoved.desc': 'Changes saved successfully',
    'profile.saveSuccess.title': 'Profile saved successfully!',
    'profile.saveSuccess.desc': 'All your changes have been saved',
    'profile.saveFailed.title': 'Failed to save profile',
    'profile.saveFailed.desc': 'Please check your information and try again',
    'profile.networkError.title': 'Network error',
    'profile.networkError.desc': 'Unable to complete the operation. Please try again.',
    'profile.verif.loading': 'Loading verification data...',
    'profile.verif.status': 'Verification status:',
    'profile.verif.identityVerified': '✅ Your identity has been verified successfully!',
    'profile.verif.rejected': '❌ Your verification was rejected. Please upload new documents and try again.',
    'profile.verif.pending': '⏳ Your documents are being reviewed. We will notify you within 24–48 hours.',
    'profile.verif.pendingNote': 'Your documents were submitted for review. We will notify you by email.',
    'profile.verif.approvedNote': 'Your documents have been successfully verified.',
    'profile.verif.instructions': 'Please upload clear photos of your government-issued ID (passport, driver’s license, etc.)',
    'profile.verif.frontTitle': 'Document Front Side',
    'profile.verif.frontDesc': 'Upload the front side. Ensure all text is readable.',
    'profile.verif.backTitle': 'Document Back Side',
    'profile.verif.backDesc': 'Upload the back side or a selfie with your ID.',
    'profile.verif.submit': 'Submit for Review',
    'profile.verif.submitting': 'Submitting...',
    'profile.verif.lastSubmitted': 'Last submitted:',
    'profile.verif.notAuthorized.title': 'Not authorized',
    'profile.verif.notAuthorized.desc': 'Please log in to upload documents',
    'profile.verif.saveDocError.title': 'Failed to save document',
    'profile.verif.saveDocError.desc': 'Please try again later',
    'profile.verif.docSaved.title': 'Document saved!',
    'profile.verif.docSaved.uploaded': 'Document uploaded successfully',
    'profile.verif.docSaved.removed': 'Document removed successfully',
    'profile.verif.docsRequired.title': 'Documents required',
    'profile.verif.docsRequired.desc': 'Please upload front and back photos',
    'profile.verif.submitFailed.title': 'Submission failed',
    'profile.verif.submitFailed.desc': 'Unable to submit documents. Please try again.',
    'profile.2fa.loading': 'Loading 2FA...',
    'profile.2fa.recommend': 'We recommend setting up two-factor authentication (2FA) to protect your account.',
    'profile.2fa.enabled': '2FA enabled',
    'profile.2fa.disabled': '2FA disabled',
    'profile.2fa.setup': 'Set up 2FA',
    'profile.2fa.preparing': 'Preparing...',
    'profile.2fa.disable': 'Disable 2FA',
    'profile.2fa.disabling': 'Disabling...',
    'profile.2fa.scanQr': 'Scan this QR code in Google Authenticator or enter the secret manually.',
    'profile.2fa.openOtpauth': 'Open otpauth link',
    'profile.2fa.secret': 'Secret:',
    'profile.2fa.enterCode': 'Enter 6-digit code',
    'profile.2fa.verify': 'Verify',
    'profile.2fa.verifying': 'Verifying...',
    'profile.password.old': 'Old Password:',
    'profile.password.new': 'New Password:',
    'profile.password.repeat': 'Repeat New Password:',
    'profile.password.help': 'If you do not remember your old password, please contact Customer Support',
    'profile.password.change': 'Change',
  },
  es: {
    // Auth pages
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.accountRegistration': 'Registro de Cuenta',
    'auth.passwordRecovery': 'Recuperación de Contraseña',
    'auth.email': 'Email',
    'auth.password': 'Contraseña',
    'auth.name': 'Nombre',
    'auth.surname': 'Apellido',
    'auth.phone': 'Número de teléfono',
    'auth.enterPhoneNumber': 'Ingrese número de teléfono',
    'auth.repeatPassword': 'Repetir contraseña',
    'auth.rememberMe': 'Recordarme',
    'auth.forgotPassword': '¿Olvidaste la contraseña?',
    'auth.signIn': 'Iniciar Sesión',
    'auth.signUp': 'Registrarse',
    'auth.alreadyHaveAccount': '¿Ya tienes cuenta?',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.continue': 'Continuar',
    'auth.backToLogin': 'Volver al inicio de sesión',
    'auth.byRegisteringAccept': 'Al registrarme, acepto la',
    'auth.privacyPolicy': 'Política de Privacidad',
    'auth.detectingCountry': 'Detectando país...',
    'auth.detected': 'Detectado',
    'auth.createAccountDescription': 'Crea una nueva cuenta para comenzar',
    'auth.loginDescription': 'Inicia sesión en tu cuenta',
    'auth.forgotPasswordDescription': 'Ingresa el email para recuperar la contraseña',
    
    // Validation messages
    'validation.passwordsNotMatch': 'Las contraseñas no coinciden',
    'validation.passwordMinLength': 'La contraseña debe tener al menos 6 caracteres',
    'validation.invalidPhoneFormat': 'Formato de número de teléfono inválido',
    'validation.acceptPrivacy': 'Debes aceptar la Política de Privacidad',
    'validation.allFieldsRequired': 'Todos los campos son obligatorios',
    'validation.userExists': 'El usuario con este email ya existe',
    'validation.invalidCredentials': 'Email o contraseña inválidos',
    'validation.registrationSuccess': '¡Registro exitoso! Ahora inicia sesión.',
    'validation.registrationError': 'Ocurrió un error durante el registro',
    'validation.loginError': 'Ocurrió un error durante el inicio de sesión',
    'validation.passwordResetSent': 'Si existe una cuenta con este email, se han enviado instrucciones de recuperación de contraseña a tu correo electrónico',
    'validation.emailRequired': 'El email es obligatorio',
    'validation.passwordRequired': 'La contraseña es obligatoria',
    'validation.nameRequired': 'El nombre es obligatorio',
    'validation.surnameRequired': 'El apellido es obligatorio',
    'validation.phoneRequired': 'El número de teléfono es obligatorio',
    'validation.invalidEmail': 'Por favor ingresa un email válido',
    'validation.passwordTooShort': 'La contraseña es muy corta',
    'validation.passwordTooLong': 'La contraseña es muy larga',
    'validation.nameTooShort': 'El nombre es muy corto',
    'validation.nameTooLong': 'El nombre es muy largo',
    
    // Dashboard
    'dashboard.hello': 'Hola',
    'dashboard.portfolio': 'Portafolio',
    'dashboard.transactions': 'Transacciones',
    'dashboard.analytics': 'Analíticas',
    'dashboard.totalValue': 'Valor total',
    'dashboard.totalOperations': 'Operaciones totales',
    'dashboard.profitability': 'Rentabilidad',
    'dashboard.logout': 'Cerrar sesión',
    'dashboard.manageInvestments': 'Gestiona tus inversiones',
    'dashboard.operationHistory': 'Historial de tus operaciones',
    'dashboard.statisticsReports': 'Estadísticas e informes',
    
    // Common
    'common.loading': 'Cargando...',
    'common.signingIn': 'Iniciando sesión...',
    'common.registering': 'Registrando...',
    'common.sending': 'Enviando...',
  }
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  // IMPORTANT: Use a deterministic initial value for SSR to avoid hydration mismatches.
  // Then, after mount, read the saved language from localStorage and update state.
  const [language, setLanguage] = useState<Language>('ru')
  const [hydrated, setHydrated] = useState(false)

  useEffect(() => {
    try {
      const saved = (typeof window !== 'undefined' ? window.localStorage.getItem('language') : null) as Language | null
      if (saved === 'en' || saved === 'ru' || saved === 'de') {
        setLanguage(saved)
      }
      setHydrated(true)
    } catch {}
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    try {
      window.localStorage.setItem('language', lang)
      // persist also to cookie for potential SSR/middleware usage
      document.cookie = `language=${lang}; path=/; max-age=31536000`
    } catch {}
  }

  const t = (key: string, params?: Record<string, string | number>): string => {
    const dict = (translations as any)[language] || (translations as any)['en'] || {}
    const raw = (dict as any)[key] || key
    if (!params) return raw
    return Object.keys(params).reduce((acc, k) => acc.replace(new RegExp(`\\{${k}\\}`, 'g'), String(params[k]!)), raw)
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {hydrated ? children : null}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
